// ProductData.js
const products = [
    {
      id: 1,
      primaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273744/3-1_nsgqfk.webp",
      secondaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273722/1-1_jkssrf.webp",
      name: "Quibusdam ratione",
      price: 40,
      oldPrice: 50.99,
      rating: 3.5,
      isHot: true,
      quantity: 0,
    },
    {
      id: 2,
      primaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273744/3-1_nsgqfk.webp",
      secondaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273722/1-1_jkssrf.webp",
      name: "Quibusdam ratione",
      price: 40,
      oldPrice: 50.99,
      rating: 3.5,
      isHot: true,
      quantity: 0,
    },
    {
      id: 3,
      primaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273744/3-1_nsgqfk.webp",
      secondaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273722/1-1_jkssrf.webp",
      name: "Quibusdam ratione",
      price: 40,
      oldPrice: 50.99,
      rating: 3.5,
      isHot: true,
      quantity: 0,
    },
    {
      id: 4,
      primaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273744/3-1_nsgqfk.webp",
      secondaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273722/1-1_jkssrf.webp",
      name: "Quibusdam ratione",
      price: 40,
      oldPrice: 50.99,
      rating: 3.5,
      isHot: true,
      quantity: 0,
    },
    {
      id: 5,
      primaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273744/3-1_nsgqfk.webp",
      secondaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273722/1-1_jkssrf.webp",
      name: "Quibusdam ratione",
      price: 40,
      oldPrice: 50.99,
      rating: 3.5,
      isHot: true,
      quantity: 0,
    },
    {
      id: 6,
      primaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273744/3-1_nsgqfk.webp",
      secondaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273722/1-1_jkssrf.webp",
      name: "Quibusdam ratione",
      price: 40,
      oldPrice: 50.99,
      rating: 3.5,
      isHot: true,
      quantity: 0,
    },
    {
      id: 7,
      primaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273744/3-1_nsgqfk.webp",
      secondaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273722/1-1_jkssrf.webp",
      name: "Quibusdam ratione",
      price: 40,
      oldPrice: 50.99,
      rating: 3.5,
      isHot: true,
      quantity: 0,
    },
    {
      id: 8,
      primaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273744/3-1_nsgqfk.webp",
      secondaryImg: "https://res.cloudinary.com/dsfems7vy/image/upload/v1688273722/1-1_jkssrf.webp",
      name: "Quibusdam ratione",
      price: 40,
      oldPrice: 50.99,
      rating: 3.5,
      isHot: true,
      quantity: 0,
    },
  ];
  
  export default products;
  