// ProductData.js
export const products = [
  {
    id: 1,
    primaryImg: "../images/shirt-1.webp",
    secondaryImg: "../images/shirt-2.webp",
    name: "Quibusdam ratione",
    price: 46.91,
    oldPrice: 50.99,
    rating: 3.5,
    quantity: 0,
  },
  {
    id: 2,
    primaryImg: "../images/shirt-1.webp",
    secondaryImg: "../images/shirt-2.webp",
    name: "Quibusdam ratione",
    price: 46.91,
    oldPrice: 50.99,
    rating: 3.5,
    quantity: 0,
  },
  {
    id: 3,
    primaryImg: "../images/shirt-1.webp",
    secondaryImg: "../images/shirt-2.webp",
    name: "Quibusdam ratione",
    price: 46.91,
    oldPrice: 50.99,
    rating: 3.5,
    quantity: 0,
  },
  {
    id: 4,
    primaryImg: "../images/shirt-1.webp",
    secondaryImg: "../images/shirt-2.webp",
    name: "Quibusdam ratione",
    price: 46.91,
    oldPrice: 50.9,
    rating: 3.5,
    quantity: 0,
  },
  {
    id: 5,
    primaryImg: "../images/shirt-1.webp",
    secondaryImg: "../images/shirt-2.webp",
    name: "Quibusdam ratione",
    price: 46.91,
    oldPrice: 50.99,
    rating: 3.5,
    quantity: 0,
  },
  {
    id: 6,
    primaryImg: "../images/shirt-1.webp",
    secondaryImg: "../images/shirt-2.webp",
    name: "Quibusdam ratione",
    price: 46.91,
    oldPrice: 50.99,
    rating: 3.5,
    quantity: 0,
  },
  {
    id: 7,
    primaryImg: "../images/shirt-1.webp",
    secondaryImg: "../images/shirt-2.webp",
    name: "Quibusdam ratione",
    price: 46.91,
    oldPrice: 50.99,
    rating: 3.5,
    quantity: 0,
  },
  {
    id: 8,
    primaryImg: "../images/shirt-1.webp",
    secondaryImg: "../images/shirt-2.webp",
    name: "Quibusdam ratione",
    price: 46.91,
    oldPrice: 50.99,
    rating: 3.5,
    quantity: 0,
  },
];

export default products;
